# Use an official Node runtime as a parent image
FROM node:14.17.3

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

# Install dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    apt-utils \
    procps \
    nano \
    git \
    unzip \
    curl \
    build-essential \
    imagemagick \
    zip && \
    # clean up
    rm -fr /tmp/* && \
    rm -rf /var/list/apt/* && \
    rm -r /var/lib/apt/lists/* && \
    apt-get clean